# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

GMAIL_USERNAME: TU_NOMBRE
GMAIL_PASSWORD: TU_PASSWORD
MAILCHIMP_API_KEY: RHBiRbF7lHw7gJUwc6EmOA
MAILCHIMP_LIST_ID: Tu List_ID de MailChimp
DOMAIN_NAME: 
OWNER_EMAIL: Propietario de e-mail

#DATOS PARA LA BASE DE DATOS
USERNAME_DB: boris
PASSWORD_DB: '19242323'

#cambiar por el correo corporativo admin@alerasin.com
MANDRILL_USERNAME: tecnodetalles@gmail.com
 
MANDRILL_API_KEY: XCu7HqUjZJZZ-fMGhKX1Bw

#CARRIERWAVE
AWS_KEY: AKIAJHJFU3NHMAMZNBIQ
AWS_SECRET_KEY: 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
AWS_REGION: us-west-2
AWS_BUCKET: alerasindev
